Translation initial environment (min change)
kubernetes/kubernetes-docs-ja pull request #24
Opened 2018-09-07 08:09 UTC by zembutsu

fix #22 , This is the alternative #23 
I minimized repository changes and made it possible to review hugo

2018-09-07 08:15 UTC, zembutsu commented
Preview is here.
https://deploy-preview-24--kubernetes-docs-ja.netlify.com/jp/
Nothing is displayed here. Because there is no content in jp directory yet.

2018-09-07 09:30 UTC, tnir requested changes

2018-09-07 09:30 UTC, tnir commented on config.toml
> -contentDir = "content/cn"
`languages.cn` はコメントアウトせずに `languages.jp` の追加だけにしていただけますでしょうか。

2018-09-07 10:33 UTC, tnir commented
@zembutsu Thanks. Due to this PR, finally I found the root cause of `hugo` error 😄 so I created kubernetes/website#10219. After that merged and then ported to this repo, it looks better than creating new files especially in this case on master (1.12), we do not have such YAML files added in this PR 😢 

What do you think?

2018-09-11 00:12 UTC, zembutsu commented on config.toml
> -contentDir = "content/cn"
もどしました！

2018-09-11 09:45 UTC, tnir commented
Closed in favor of #27 🙇 /cc @zembutsu

2018-09-11 09:45 UTC, closed without merging

2018-09-11 09:52 UTC, cstoku commented on config.toml
> +[languages.jp]
こちら `languages.ja` ではないでしょうか？

2018-09-11 09:52 UTC, cstoku commented on config.toml
> +contentDir = "content/jp"
こちら `content/ja` ではないでしょうか？

2018-09-11 09:59 UTC, cstoku commented
@tnir もしよければ [こちら](https://prow.k8s.io/command-help) にある `/close` コマンド使っていただけると！(極力botのコマンド経由で操作お願いします :bowing_man: )

2018-09-11 10:05 UTC, tnir commented
すみません。。。 🙇 気をつけます。

@cstoku しかし、こちらが https://kubernetes-docs-ja.netlify.com/ja/ が一番早くレビューできるPRなので、クローズしてよかったのか分かりませんね。

2018-09-11 10:09 UTC, cstoku commented
もちろん`/reopen` も全然出来ます。
ただこのPRは以前のご操作のRevertのCommit含んでたりもするので一旦整理してもらって再度PR出してもらうのがよさそうだと思っています。
@zembutsu 上記でいかがでしょう？