日本語ドキュメントのindex.html
kubernetes/kubernetes-docs-ja pull request #25
Opened 2018-09-10 08:00 UTC by zembutsu

`/content/jp/_index.html` の翻訳です。

![Allow edits from maintainers checkbox](https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)

2018-09-12 14:01 UTC, tnir commented
@zembutsu Could you rebase this to enable review apps with netlify?

2018-09-12 14:15 UTC, tnir requested changes
コメントしました。

2018-09-12 14:15 UTC, tnir commented on content/jp/_index.html
> +        <h3 class="center">Kubernetes 機能</h3>
「Kubernetes の機能」でどうでしょう？

2018-09-12 14:15 UTC, tnir commented on content/jp/_index.html
> +                <p>障害が起こればコンテナを再起動し、ノードが壊れればコンテナの再配置と再スケジュールをし、定義したヘルスチェックの応答がなければコンテナを停止し、クライアントに提供する準備が整わなければ広報(advertise)しません。</p>
advertise=広告にすると、アプリケーションエンジニアには分かりにくいですかね？

2018-09-12 14:15 UTC, tnir commented on content/jp/_index.html
> +                <p>サービス・ディスカバリ機構になれていなくても、アプリケーションに手を加えることなく利用できる。Kubernetes はコンテナに対して IP アドレスとコンテナ群に対する１つの DNS 名をあたえ、相互に負荷分散できるようにします。</p>
ここだけ「です・ます」が「だ・である」になっているので、「利用できる」→「利用できます」がよさそうです。

2018-09-12 14:15 UTC, tnir commented on content/jp/_index.html
> +                <p>Kubernetes はアプリケーションの正常性を確保したまま、全てのインスタンスを停止せず、アプリケーションや設定に対する変更を徐々に適用する。もし何か問題が起これば、Kubernetes は変更に対してロールバックすします</p>
s/すします/します/

2018-09-12 14:15 UTC, tnir commented on content/jp/_index.html
> +                <p>Kubernetes はアプリケーションの正常性を確保したまま、全てのインスタンスを停止せず、アプリケーションや設定に対する変更を徐々に適用する。もし何か問題が起これば、Kubernetes は変更に対してロールバックすします</p>
「適用する」→「適用します」

2018-09-12 14:15 UTC, tnir commented on content/jp/_index.html
> +                <p>シークレットとアプリケーション設定の展開と更新には、イメージの再構築やスタック設定内でシークレットを露出しない。</p>
「露出しない」→「露出しません」

2018-09-12 14:15 UTC, tnir commented on content/jp/_index.html
> +                <p>eBay の内部は OpenStack 上の Kubernetes とコンテナに移行</p>
「eBay の内部は」→「eBay の内部システムを」はどうでしょう？

2018-09-12 14:15 UTC, tnir commented on content/jp/_index.html
> +                <p>時前の「クラスタ」から Kubernetes への移行</p>
「時前の」→「自前の」

2018-09-12 22:02 UTC, zembutsu commented on content/jp/_index.html
> +                <p>障害が起こればコンテナを再起動し、ノードが壊れればコンテナの再配置と再スケジュールをし、定義したヘルスチェックの応答がなければコンテナを停止し、クライアントに提供する準備が整わなければ広報(advertise)しません。</p>
広告(advertise)と括弧付きにしました。ここは悩んだ所、日本語の広告というよりはbroadcast、通知的な意味合いがありそうでしたが、広告にします。

2018-09-12 22:04 UTC, zembutsu commented on content/jp/_index.html
> +                <p>サービス・ディスカバリ機構になれていなくても、アプリケーションに手を加えることなく利用できる。Kubernetes はコンテナに対して IP アドレスとコンテナ群に対する１つの DNS 名をあたえ、相互に負荷分散できるようにします。</p>
統一しますね。

2018-09-12 22:04 UTC, zembutsu commented
もろもろフィードバックありがとうございます！

2018-09-13 00:04 UTC, zembutsu commented
Preview is here.
https://deploy-preview-25--kubernetes-docs-ja.netlify.com/ja/

2018-09-13 01:26 UTC, tnir requested changes
@zembutsu typo 2箇所、改善提案4箇所レビューしました。

2018-09-13 01:26 UTC, tnir commented on content/ja/_index.html
> +            <p>oogle が毎週 10 億ものコンテナを動かすのと同じ方式で設計しているため、Kubernetes は皆さんの運用チームを増員しなくてもスケールできます。</p>
s/oogle/Google/ ですかね。

2018-09-13 01:26 UTC, tnir commented on content/ja/_index.html
> +            <h4>成長は継続</h4>
"Never Outgrow"なので、成長が継続するという意図よりは、（続く文にもある通り）大きくなりすぎる（複雑になりすぎる）ことがないということかと思うので、「肥大化しない」（「肥大化することはありません」だと原文の簡潔さが損なわれてしまうので）あたりはどうでしょうか？

2018-09-13 01:26 UTC, tnir commented on content/ja/_index.html
> +                <p>リソース要件と他の制限に基づき、可用性を犠牲にせず、コンテナを自動的に配置します。リソースの稼働率を高め、リソースを更に制限するために、クリティカルおよびベスト・エフォートなワーククロードを組み合わせます。</p>
「クリティカルおよびベスト・エフォートなワーククロードを組み合わせることで、リソースの稼働率を高め、リソースをさらに節約できます。」くらいでどうでしょう。save resourcesは制限というよりは節約という意図かと思います。

2018-09-13 01:26 UTC, tnir commented on content/ja/_index.html
> +                <p>簡単なコマンドか UI あるいは CPU 使用率に基づき、アプリケーションを自動的にスケールアップ・ダウンします。</p>
「基づき」にかかる並列部分が分かりにくいので、「簡単なコマンドか UI あるいは CPU 使用率閾値により」でどうでしょう。

2018-09-13 01:26 UTC, tnir commented on content/ja/_index.html
> +                <p>シークレットとアプリケーション設定の展開と更新には、イメージの再構築やスタック設定内でシークレットを露出しません。</p>
イメージの再構築[...]を露出しません、というのは変な感じがします。

「イメージの再構築不要で、スタック設定内でシークレットを露出することなく、シークレットとアプリケーション設定の展開と更新できます。」くらいでどうでしょう。

2018-09-13 01:26 UTC, tnir commented on content/ja/_index.html
> +                <p>ローカル・ストレージや <a href="https://cloud.google.com/storage/">GCP</a> や <a href="https://aws.amazon.com/products/storage/">AWS</a>どのパブリック・クラウド・プロバイダ、あるいは NFS や iSCSI、Gluster、Ceph、Cinder、
s/どの/などの/

2018-09-13 01:36 UTC, nasa9084 commented on content/ja/_index.html
> +                <p>簡単なコマンドか UI あるいは CPU 使用率に基づき、アプリケーションを自動的にスケールアップ・ダウンします。</p>
「簡単なコマンドか UI や CPU 使用率に基づき」くらいでも良いような気がします

2018-09-13 01:37 UTC, nasa9084 commented on content/ja/_index.html
> +title: "プロダクション級コンテナ・オーケストレーション"
ほぼただカタカナにしただけなので、無理に訳さなくても良いような気がします(もちろんこれでもよいとはおもいます)

2018-09-13 01:42 UTC, nasa9084 commented
/assign @nasa9084

2018-09-14 06:21 UTC, tnir commented
/hold

2018-09-14 07:09 UTC, nasa9084 commented
@tnir: why hold this PR?

2018-10-15 22:00 UTC, closed without merging