add Japanese configuration into toml
kubernetes/kubernetes-docs-ja pull request #28
Opened 2018-09-11 10:38 UTC by tnir

To start language.jp in hugo, this PR replaces #24, with keeping the original concept by @zembutsu and author information.

Co-authored-by: Takuya Noguchi <takninnovationresearch@gmail.com>

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

![Allow edits from maintainers checkbox](https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)

2018-09-11 10:38 UTC, tnir commented
On my local `hugo` does work well as follow:
```
$ hugo

                   |  EN  | CN  | JP
+------------------+------+-----+-----+
  Pages            | 1045 |   4 |   4
  Paginator pages  |    0 |   0 |   0
  Non-page files   |  265 |  80 |  80
  Static files     |  732 | 732 | 732
  Processed images |    0 |   0 |   0
  Aliases          |    2 |   1 |   1
  Sitemaps         |    2 |   1 |   1
  Cleaned          |    0 |   0 |   0

Total in 1244 ms
```

2018-09-11 10:42 UTC, tnir commented
手間がかかってしまうので、@zembutsu の表記のままPR作り直しました。

/assign @cstoku

2018-09-11 10:55 UTC, cstoku requested changes

2018-09-11 10:55 UTC, cstoku commented on config.toml
> +[languages.jp]
`languages.ja` に変更お願いします！

2018-09-11 10:55 UTC, cstoku commented on config.toml
> +contentDir = "content/jp"
`content/ja` に変更お願いします！

2018-09-12 00:42 UTC, tnir commented on config.toml
> +[languages.jp]
おお、ノーロックでした 🙇

2018-09-12 00:43 UTC, tnir commented
@cstoku Could you review this again?

2018-09-12 00:54 UTC, tnir commented
/cc @zembutsu

2018-09-12 01:28 UTC, nasa9084 commented
/lgtm

2018-09-12 01:28 UTC, nasa9084 commented
/lgtm

2018-09-12 01:29 UTC, nasa9084 commented
lgtm

2018-09-12 01:30 UTC, nasa9084 approved these changes

2018-09-12 04:12 UTC, cstoku commented
/lgtm
/approve

2018-09-12 04:13 UTC, merged