merge translation from kubernetes-docs-ja/website
kubernetes/kubernetes-docs-ja pull request #8
Opened 2018-08-24 16:31 UTC by nasa9084

Copied my translation works from kubernetes-docs-ja/website repository.
This also configure japanese content directory, take in changes in kubernetes/website since I have forked to kubernetes-docs-ja/website.

2018-08-24 16:32 UTC, nasa9084 commented
/assign @cstoku

2018-08-24 16:33 UTC, nasa9084 commented
this PR also solves #7

2018-08-24 21:32 UTC, tnir requested changes
原文と比較せずざっと読んだ結果でコメントしました。

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
コンセプト vs 概念？

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +加えて、Kubernetesはコントローラと呼ばれる、高度な抽象概念を持っています。コントーらは基本オブジェクトの上に構築され、追加の機能性や利便性を提供します。これらは、次のものを含みます:
s/コントーら/コントローラ/

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +Kubernetes masterはクラスタの目的の状態を維持する責務を負います。 `kubectl`コマンドラインインターフェースを使うなどしてKubernetesと通信を行ったとき、あなたはクラスタのKubernetes masterと通信をしています。
s/Kubernetes master/Kubernetes Master/g

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +クラスタのノードはアプリケーションやクラウドワークフローを実行するマシン(VMや物理マシンなど)です。Kubernetes masterはそれぞれのノードを制御します。つまり、あなたがノードと直接対話することはほとんどありません。
s/Kubernetes master/Kubernetes Master/

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/overview/components.md
> +このドキュメントでは、動作するKubernetes clusterに必要なバイナリコンポーネントについて説明します。
Kubernetes cluster vs Kubernetesクラスタ

I'd say +1 for Kubernetesクラスタ

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/overview/components.md
> +[cloud-controller-manager](/docs/tasks/administer-cluster/running-cloud-controller/)は、基盤となるクラウドプロバイダーと対話するコントローラを実行します。cloud-controller-managerはKubernetes 1.6ではアルファ機能です。
1.11でベータになったのに `Kubernetes 1.6ではアルファ機能です` は少し引っかかりますね。（ベースが1.10なのでしょうがないけど）

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +APIへのリモートアクセスについては、[access doc](/docs/admin/accessing-the-api)で議論されています。.
Remove the trailing `.`

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +Kubernetesはクラスタ内部のコミュニケーションで主に試用するために、Protbufベースのシリアライゼーションフォーマットを実装しています。これは[design proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf
s/Protbuf/Protobuf/

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +Kubernetesはクラスタ内部のコミュニケーションで主に試用するために、Protbufベースのシリアライゼーションフォーマットを実装しています。これは[design proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf
s/試用/使用/

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/editdocs.md
> +<p><a class="button" href="https://github.com/kubernetes/website/">このサイトのソースコードを表示する</a></p>
ここはk/websiteとk/k-docs-jaの両方を説明したほうがいいかもしれませんね。

2018-08-24 21:32 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +Kubernetesで作業をするためには、 *Kubernetes APIオブジェクト* を使用してクラスタの *状態* を記述します。どのようなアプリケーションやワークロードを動作させたいのか、どのようなコンテナイメージを使うのか、レプリカの数、どのようなネットワークやディスクリソースがあるのか、などです。通常は`kubectl`というコマンドラインインターフェースを使用し、Kubernete
s/出来ます/できます/g

cf. "公用文における漢字使用等について"

2018-08-25 02:36 UTC, nasa9084 commented on content/ja/docs/concepts/overview/components.md
> +[cloud-controller-manager](/docs/tasks/administer-cluster/running-cloud-controller/)は、基盤となるクラウドプロバイダーと対話するコントローラを実行します。cloud-controller-managerはKubernetes 1.6ではアルファ機能です。
まぁ、1.10ベースなので・・・

2018-08-25 02:39 UTC, nasa9084 commented on content/ja/docs/editdocs.md
> +<p><a class="button" href="https://github.com/kubernetes/website/">このサイトのソースコードを表示する</a></p>
今後議論が必要かと思うので、この場では単なる訳に抑えて、issueを上げておきます

2018-08-25 02:40 UTC, nasa9084 commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
タイトルを「コンセプト」にしたので、とりあえずコンセプトでそろえた方が良いかと思ってます(勿論異論は認めますので、議論したい

2018-08-25 02:41 UTC, nasa9084 commented on content/ja/docs/concepts/overview/components.md
> +このドキュメントでは、動作するKubernetes clusterに必要なバイナリコンポーネントについて説明します。
確かにそちらの方がよさそう

2018-08-25 02:43 UTC, nasa9084 commented
@tnir thanks. I fixed that I can fix immediately.

2018-08-25 02:50 UTC, nasa9084 commented on content/ja/docs/editdocs.md
> +<p><a class="button" href="https://github.com/kubernetes/website/">このサイトのソースコードを表示する</a></p>
issue #13

2018-08-26 08:22 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
すみません。concept => 概念、はそれで問題なかったです。（"abstract concept" みたいな原文表現が存在していて、それが抽象概念と訳されているのかと思ってのコメントでした（が実際には原文にはそのような表現はなかったです））

" ... the abstractions Kubernetes uses [...]" は「抽象化」がいいのでは？（という指摘のつもりでした）

2018-08-26 10:10 UTC, tnir commented
@nasa9084 Thanks for fixing them. If you don't mind, could you edit more through all files:

- s/出来ます/できます/
- s/出来た/できた/

2018-08-27 00:53 UTC, nasa9084 commented
@tnir fixed.

2018-08-28 09:44 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
@nasa9084 こちらはどうでしょう？

2018-08-28 11:12 UTC, makocchi-git approved these changes
lgtm

2018-08-28 11:26 UTC, cstoku requested changes

2018-08-28 11:26 UTC, cstoku commented on config.toml
> -
`[languages.cn]` は消しちゃいましょう！

2018-08-28 11:26 UTC, cstoku commented on content/ja/docs/concepts/overview/components.md
> +reviewers:
`reviewers` のブロックを消してください！

2018-08-28 11:26 UTC, cstoku commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +reviewers:
`reviewers` のブロックを消してください！

2018-08-28 11:27 UTC, cstoku commented
訳自体は自分も良いと思います！

2018-08-28 12:10 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +Kubernetesで作業をするためには、 *Kubernetes APIオブジェクト* を使用してクラスタの *状態* を記述します。どのようなアプリケーションやワークロードを動作させたいのか、どのようなコンテナイメージを使うのか、レプリカの数、どのようなネットワークやディスクリソースがあるのか、などです。通常は`kubectl`というコマンドラインインターフェースを使用し、Kubernete
s/直接し要すして/直接操作して/

2018-08-28 12:17 UTC, tnir commented on content/ja/docs/concepts/overview/components.md
> +しかし、単純化のために、セットアップスクリプトは通常、すべてのマスターコンポーネントを同じマシン上で実行し、そのマシン上ではユーザのコンテナを実行しません。
s/マスターコンポーネント/Masterコンポーネント/g

2018-08-28 14:15 UTC, nasa9084 commented on config.toml
> -
最終的にk/websiteにmergeされることを考えると、`[languages.cn]`は消しちゃだめなんじゃないかと思うんですが・・・

2018-08-28 14:23 UTC, nasa9084 commented on content/ja/docs/concepts/overview/components.md
> +しかし、単純化のために、セットアップスクリプトは通常、すべてのマスターコンポーネントを同じマシン上で実行し、そのマシン上ではユーザのコンテナを実行しません。
Nodeやcontroller-managerなど、他のコンポーネントとのバランスを考えると、英字でMasterのままの方が良いように思えるんですが、どうでしょうか？

2018-08-28 14:26 UTC, nasa9084 commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
`Kubernetesがクラスタを表現するために使用する抽象概念について学び` → `Kubernetesがクラスタを表現するために使用する抽象化について学び` ということでしょうか？
「コンセプト」という章題の通り、Kubernetes上での概念について学ぶ章なので、「抽象化について学び」だと意味合いが違うように思えます。

2018-08-29 01:56 UTC, cstoku commented on config.toml
> -
このリポジトリ最終的に `k/website` にmergeされるんですかね・・・？
されるとしてもgit的にも別物なので結構特殊なことをしそうですが。最終的なリリースフローの話はまだどこにも出てなくて個人ではよくわかってないです。(この辺の問題は後々明確にしていきます)

あっても特に問題はない設定なので一旦残しておきましょうか、すいません！ 🙇

2018-08-29 02:54 UTC, nasa9084 commented on config.toml
> -
残しておく、ということでchange requestを消してもらえると良いかと思います

2018-08-29 03:01 UTC, cstoku approved these changes

2018-08-31 06:54 UTC, MasayaAoyama commented
/lgtm

2018-08-31 08:36 UTC, tnir commented on content/ja/docs/concepts/overview/components.md
> +しかし、単純化のために、セットアップスクリプトは通常、すべてのマスターコンポーネントを同じマシン上で実行し、そのマシン上ではユーザのコンテナを実行しません。
「Masterコンポーネント」「マスターコンポーネント」どちらでもいいんですが、統一されていないので、（ここ以外で利用されている「Masterコンポーネント」に）統一をお願いします、の意味でした。

2018-08-31 08:37 UTC, nasa9084 commented on content/ja/docs/concepts/overview/components.md
> +しかし、単純化のために、セットアップスクリプトは通常、すべてのマスターコンポーネントを同じマシン上で実行し、そのマシン上ではユーザのコンテナを実行しません。
これは失礼しました。修正します。

2018-08-31 11:06 UTC, MasayaAoyama commented on content/ja/docs/concepts/_index.md
> +## 全体
全体　はちょっと微妙な気もします

2018-08-31 11:06 UTC, MasayaAoyama commented on content/ja/docs/concepts/_index.md
> +## 全体
概要とか

2018-08-31 11:06 UTC, MasayaAoyama commented on content/ja/docs/concepts/_index.md
> +Kubernetesで作業をするためには、 *Kubernetes APIオブジェクト* を使用してクラスタの *状態* を記述します。どのようなアプリケーションやワークロードを動作させたいのか、どのようなコンテナイメージを使うのか、レプリカの数、どのようなネットワークやディスクリソースがあるのか、などです。通常は`kubectl`というコマンドラインインターフェースを使用し、Kubernete
日本語化するのと、翻訳するのとちょっと違う気がするので、個々らへんはどうするか決めた方がいい気もします。
今の段階だと、日本語化というより翻訳って感じがしていて、Google翻訳＋αくらいの精度かなという気もします。

2018-08-31 11:06 UTC, MasayaAoyama commented on content/ja/docs/concepts/overview/components.md
> +cloud-controller-managerはクラウドベンダーのコードとKubernetesコアを互いに独立して進化させることを可能にします。以前のリリースでは、コアKubernetesコードはクラウドプロバイダ固有の機能コードに依存していました。将来のリリースでは、クラウドベンダー特有のコードはクラウドベンダー自身によって管理され、cloud-controller-managerにリンクし
進化　っていうと微妙な気がするので、日本語的に他の言葉のほうがよいかもです。
アップデートとか、機能追加とか

2018-08-31 11:06 UTC, MasayaAoyama commented on content/ja/docs/concepts/overview/components.md
> +cloud-controller-managerはクラウドベンダーのコードとKubernetesコアを互いに独立して進化させることを可能にします。以前のリリースでは、コアKubernetesコードはクラウドプロバイダ固有の機能コードに依存していました。将来のリリースでは、クラウドベンダー特有のコードはクラウドベンダー自身によって管理され、cloud-controller-managerにリンクし
コアKubernetesコード
も変なきがして
Kubernetes本体のコード　とか

2018-08-31 11:06 UTC, MasayaAoyama commented on content/ja/docs/concepts/overview/components.md
> +  * Node Controller: ノードが停止した後、クラウド上でノードが削除されたかどうかを調べるため
なんか日本語的にイマイチパット入ってこない気がします。
調べるために利用しますとか…？

2018-08-31 13:14 UTC, nasa9084 commented on content/ja/docs/concepts/overview/components.md
> +  * Node Controller: ノードが停止した後、クラウド上でノードが削除されたかどうかを調べるため
箇条書きなので、あまり違和感ないかと思ったんですが・・・

2018-09-03 03:41 UTC, nasa9084 commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
@tnir resolveしても良いでしょうか？

2018-09-10 08:12 UTC, nasa9084 commented
@tnir @cstoku これ、すすめられます？

2018-09-10 08:12 UTC, nasa9084 commented
@tnir @cstoku ping

2018-09-10 08:38 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
@nasa9084 遅くなりすみません。ドキュメントで「抽象概念」と言われて、私はぴんと来ないので、他の方のご意見をもらってもいいでしょうか？

@cstoku @zembutsu [Concepts](https://v1-10.docs.kubernetes.io/docs/concepts/) の `abstractions` の訳について、(1) 抽象概念、(2) 抽象化、(3)その他、のどれがいいかご意見いただけないでしょうか。

2018-09-10 08:41 UTC, tnir commented on content/ja/docs/concepts/overview/components.md
> +  * Node Controller: ノードが停止した後、クラウド上でノードが削除されたかどうかを調べるため
「〜するため」は「〜役割」はどうでしょう？（ここだと「調べる役割」という表現になります）

2018-09-11 09:27 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +Kubernetesで作業をするためには、 *Kubernetes APIオブジェクト* を使用してクラスタの *状態* を記述します。どのようなアプリケーションやワークロードを動作させたいのか、どのようなコンテナイメージを使うのか、レプリカの数、どのようなネットワークやディスクリソースがあるのか、などです。通常は`kubectl`というコマンドラインインターフェースを使用し、Kubernete
@MasayaAoyama @MasayaAoyama の指摘後、こちらについては特に変更はないですが、どうしましょう？ cc @nasa9084

2018-09-11 09:27 UTC, tnir commented on content/ja/docs/concepts/_index.md
> +  * **[kube-proxy](/docs/admin/kube-proxy/)**は,各ノード上のKubernetesネットワーキングサービス実現するネットワークプロキシです。
@nasa9084 s/,/、/ お願いします。

2018-09-11 09:35 UTC, nasa9084 commented on content/ja/docs/concepts/_index.md
> +Kubernetesで作業をするためには、 *Kubernetes APIオブジェクト* を使用してクラスタの *状態* を記述します。どのようなアプリケーションやワークロードを動作させたいのか、どのようなコンテナイメージを使うのか、レプリカの数、どのようなネットワークやディスクリソースがあるのか、などです。通常は`kubectl`というコマンドラインインターフェースを使用し、Kubernete
長期的に見たら方向性を決めた方が良いと思うんですが、現段階だととりあえず日本語で読めるものがある、と言う状態に持って行くのが優先かと思ってます

2018-09-11 09:43 UTC, nasa9084 commented
@tnir changed.

2018-09-11 10:24 UTC, cstoku commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
「抽象概念」のほうがよさそうな気がしますが、文脈によっては「抽象化」と訳したほうがしっくり来る時がありますね・・・。
どちらかに振り切るなら「抽象概念」に1票です :+1:

2018-09-11 10:31 UTC, cstoku commented on content/ja/docs/concepts/overview/components.md
> +  * Node Controller: ノードが停止した後、クラウド上でノードが削除されたかどうかを調べるため
体言止めはよさそうですね。

- 削除されたかどうかを調べる役割
- 削除されたかどうかを確認

などどうでしょうか？

2018-09-13 01:34 UTC, nasa9084 commented on content/ja/docs/concepts/_index.md
> +コンセプトの章では、Kubernetesの一部や、Kubernetesがクラスタを表現するために使用する抽象概念について学び、Kubernetesがどのように動作するのかを深く理解することを助けます。
では抽象概念のままでresolveしちゃいますね

2018-09-13 01:35 UTC, nasa9084 commented
@cstoku mergeお願いします！

2018-09-13 08:52 UTC, cstoku commented
@tnir よさそうだったらReviewの方でApproveお願いします！
@nasa9084 一回現在のmasterをmergeして頂けますか？(config.tomlの変更がなくなるはず・・。)

2018-09-14 02:34 UTC, nasa9084 commented
@cstoku merged.

2018-09-14 05:58 UTC, tnir approved these changes

2018-09-14 06:05 UTC, tnir commented
@cstoku @nasa9084 遅くなりすみません。Reviewのapproveしました。

2018-09-14 06:40 UTC, cstoku commented
/lgtm
/approve

2018-09-14 09:35 UTC, cstoku commented
これはー、 `deploy/netlify` 解消させてからじゃないとダメそうな感じでしょうか・・？

2018-09-18 02:44 UTC, nasa9084 commented
#29にrebaseしたら`deploy/netlify`解消されると思います
/hold

2018-10-15 22:00 UTC, closed without merging